### PR TITLE
Made shimmer loading UI in teams/[id]

### LINKED ISSUE #27: Implement Shimmer UI Loading Effect on the Hackathon ID Page
Description:
The current loading animation on the Hackathon ID page is not visually appealing. Please remove the existing loading indicator and implement a Shimmer UI loading effect instead. This will enhance the user experience by providing a smoother and more modern loading transition.

You can refer to the attached video for a demonstration of the current loading state.

https://github.com/user-attachments/assets/73b25261-ee37-4a3b-8726-2dc81d1cbc34

### PR DESCRIPTION
**Pull request by akadeepesh**
closes #27

### CODE REVIEW

**Comment by akadeepesh** [comment]
@Yashgupta9330 Check this once! ❤️

**Comment by Yashgupta9330** [comment]
Could you kindly provide a video of the loading animation?

**Comment by akadeepesh** [comment]
Yeah sure, but it won't be on teams/[id] page, I will show you it on teams page, I'm facing issues in apply for team in localhost, without logging in it shows me that I'm signed up and redirects me to dashboard. You'll get the idea and verify it by allowing vercel to deploy branch

**Comment by akadeepesh** [comment]
### There you go

[Screencast_20241005_150456.webm](https://github.com/user-attachments/assets/9c40a8e3-7b14-4b7b-b8be-64fbec178c12)

**Pull request merged**
